import { ApiProperty } from '@nestjs/swagger';

import {
    BaseEntity as Base,
    CreateDateColumn,
    DeleteDateColumn,
    PrimaryGeneratedColumn,
    UpdateDateColumn,
} from 'typeorm';

export abstract class BaseEntity extends Base {
    @ApiProperty({
        format: 'uuid',
        example: '531200a8-c302-4819-810e-1d7340480edb',
        description: 'Unique entity identifier',
    })
    @PrimaryGeneratedColumn('uuid')
    id: string;

    @ApiProperty({
        description: 'Autogenerated creation date',
    })
    @CreateDateColumn()
    created: Date;

    @ApiProperty({
        description: 'Autogenerated last update date',
    })
    @UpdateDateColumn()
    updated: Date;

    @DeleteDateColumn()
    deleted: Date | null;
}
